# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d24268c69b8fea61641d039078b58c19"
name = "Fina Sync App"
handle = "fina-integration"
application_url = "https://fina-integration.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory,read_orders,write_orders,read_customers"

[auth]
redirect_urls = ["https://fina-integration.vercel.app/auth/callback", "https://fina-integration.vercel.app/auth/shopify/callback", "https://fina-integration.vercel.app/api/auth/callback"]

[pos]
embedded = false
